---

driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
#  additional_copy_path:
#    - test/integration/default/setup.sh
  ansible_verbosity: 2
  ansible_verbose: true
  extra_vars:
    aws_openvpn:
      s3_path: "s3://openvpn-test-bucket"
      s3_options: "--no-sign-request --endpoint-url http://localhost:8080 --no-verify-ssl"

platforms:
- name: ubuntu-14.04

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'

