---

group: stable
dist: xenial
language: python
python: "2.7"

branches:
  only:
    - develop
    - master

env:
  - ANSIBLE_INSTALL_VERSION=1.9.4

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==${ANSIBLE_INSTALL_VERSION}

script:
  - /bin/bash test/integration/default/setup.sh
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check test/integration/default/default.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml --tags "build"
  - ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml --tags "configure"
