---

language: python
python: "2.7"

branches:
  only:
    - develop
    - master

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible==1.9.4

script:
  - cp test/integration/default/setup.sh .
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check test/integration/default/default.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml
  - >
    ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
