---

sudo: required

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=1.9.3
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.9.0.1
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.8.3
  - ANSIBLE_VERSION=1.8.2
  - ANSIBLE_VERSION=1.8.1
  - ANSIBLE_VERSION=1.8

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check test/integration/default/default.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml
  - >
    ansible-playbook -i inventory --connection=local --sudo -vvvv test/integration/default/default.yml
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

