---

- name: Download OpenVPN server keys
  sudo: yes
  command: "aws s3 cp {{ openvpn_keys_s3_path }}/{{ item }} {{ openvpn_keydir }}"
  args:
    creates: "{{ openvpn_keydir }}/{{ item }}"
  with_items:
    - ca.crt
    - "dh{{ openvpn_key_size }}.pem"
    - server.crt
    - server.key
  notify:
    - restart openvpn
  when: openvpn_keys_s3_path

- name: Download OpenVPN crl
  sudo: yes
  command: "aws s3 cp {{ openvpn_keys_s3_path }}/crl.pem {{ openvpn_etcdir }}"
  notify:
    - restart openvpn
  when: openvpn_keys_s3_path and openvpn_crl_enabled

- name: Configure OpenVPN server
  sudo: yes
  template:
    src: server.conf.j2
    dest: "{{ openvpn_etcdir }}/server.conf"
  notify:
    - restart openvpn

- name: Install OpenVPN NAT iptable rule
  sudo: yes
  command: "iptables -t nat -A POSTROUTING -s {{ openvpn_snat_subnet }} -o eth0 -j MASQUERADE"
  when: openvpn_snat_subnet
