---

- name: Download OpenVPN server keys
  command: "aws s3 cp {{ aws_openvpn.s3_options }} {{ aws_openvpn.s3_path }}/{{ item }} {{ aws_openvpn.keydir }}"
  args:
    creates: "{{ aws_openvpn.keydir }}/{{ item }}"
  with_items:
    - ca.crt
    - "dh{{ aws_openvpn.key_size }}.pem"
    - server.crt
    - server.key
  notify:
    - restart openvpn

- name: Download OpenVPN crl
  command: "aws s3 cp {{ aws_openvpn.s3_path }}/crl.pem {{ aws_openvpn.etcdir }}"
  notify:
    - restart openvpn
  when: aws_openvpn.crl_enabled

- name: Configure OpenVPN server
  template:
    src: server.conf.j2
    dest: "{{ aws_openvpn.etcdir }}/server.conf"
  notify:
    - restart openvpn

#- name: Check for OpenVPN iptable rule
#  command: "iptables -t nat -C POSTROUTING -s {{ aws_openvpn.snat_subnet }} -o eth0 -j MASQUERADE"
#  register: aws_openvpn.snat_subnet_check
#  when: aws_openvpn.snat_subnet
#  run_once: true

#- name: Install OpenVPN NAT iptable rule
#  command: "iptables -t nat -A POSTROUTING -s {{ aws_openvpn.snat_subnet }} -o eth0 -j MASQUERADE"
#  when: aws_openvpn.snat_subnet
#  run_once: true
