---

- name: Add OpenVPN gpg key
  sudo: yes
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present

- name: Install OpenVPN repo
  sudo: yes
  apt_repository:
    repo: 'deb http://swupdate.openvpn.net/apt trusty main'
    state: present

- name: Install OpenVPN
  sudo: yes
  apt:
    name: "openvpn={{ openvpn_version }}"
