---

- name: start openvpn
  service:
    name: openvpn
    state: started

- name: stop openvpn
  service:
    name: openvpn
    state: stopped

- name: restart openvpn
  service:
    name: openvpn
    state: restarted
